source: ""
destination: ""
log_file: ""
workers: 8
buffer_size: 8
retry_count: 3
retry_wait: 5
include_pattern: ""
exclude_pattern: ""
recursive: true
mirror: false
dry_run: false
verbose: false
skip_newer: false
no_progress: false
preserve_mod_time: true
overwrite_existing: true
sync_mode: normal
sync_db_path: sync_state.db
include_failed: true
max_fail_count: 5
verify_only: false
verify_changed: false
verify_all: false
final_report: ""
hash_algorithm: sha256
verify_hash: true
