source: ""
destination: ""
logfile: ""
workers: 8
buffersize: 8
retrycount: 3
retrywait: 5
includepattern: ""
excludepattern: ""
recursive: true
mirror: false
dryrun: false
verbose: false
skipnewer: false
noprogress: false
preservemodtime: true
overwriteexisting: true
syncmode: normal
syncdbpath: sync_state.db
includefailed: true
maxfailcount: 5
verifyonly: false
verifychanged: false
verifyall: false
finalreport: ""
hashalgorithm: sha256
verifyhash: true
