name: CI Optimized

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

# デフォルトの権限設定
permissions:
  contents: read
  actions: read
  security-events: write
  pull-requests: read

# 環境変数の定義
env:
  CI: true
  GITHUB_ACTIONS: true
  TESTING: 1
  TEST_OUTPUT_DIR: ./test_output
  COVERAGE_DIR: ./coverage_reports
  BUILD_OUTPUT_DIR: ./build_output
  DIST_DIR: ./dist

jobs:
  # Linux/macOS テストジョブ
  test-linux:
    uses: ./.github/workflows/test.yml
    with:
      go-version: '1.21'
      platform: 'ubuntu-latest'
      coverage-flag: ${{ github.ref == 'refs/heads/develop' && 'develop' || 'unittests' }}
      timeout-minutes: 20

  test-linux-go122:
    uses: ./.github/workflows/test.yml
    with:
      go-version: '1.22'
      platform: 'ubuntu-latest'
      coverage-flag: ${{ github.ref == 'refs/heads/develop' && 'develop' || 'unittests' }}
      timeout-minutes: 20

  # Windows テストジョブ（最適化版）
  test-windows-core:
    uses: ./.github/workflows/windows-optimization.yml
    with:
      go-version: '1.21'
      test-packages: './cmd/...'
      coverage-flag: 'windows-core'
      timeout-minutes: 15

  test-windows-internal:
    uses: ./.github/workflows/windows-optimization.yml
    with:
      go-version: '1.21'
      test-packages: './internal/copier/... ./internal/database/... ./internal/filter/...'
      coverage-flag: 'windows-internal'
      timeout-minutes: 15

  test-windows-utils:
    uses: ./.github/workflows/windows-optimization.yml
    with:
      go-version: '1.21'
      test-packages: './internal/hasher/... ./internal/logger/... ./internal/stats/... ./internal/verifier/...'
      coverage-flag: 'windows-utils'
      timeout-minutes: 15

  test-windows-integration:
    uses: ./.github/workflows/windows-optimization.yml
    with:
      go-version: '1.21'
      test-packages: './tests/...'
      coverage-flag: 'windows-integration'
      timeout-minutes: 15

  # Go 1.22 Windows テストジョブ（最適化版）
  test-windows-go122-core:
    uses: ./.github/workflows/windows-optimization.yml
    with:
      go-version: '1.22'
      test-packages: './cmd/...'
      coverage-flag: 'windows-go122-core'
      timeout-minutes: 15

  test-windows-go122-internal:
    uses: ./.github/workflows/windows-optimization.yml
    with:
      go-version: '1.22'
      test-packages: './internal/copier/... ./internal/database/... ./internal/filter/...'
      coverage-flag: 'windows-go122-internal'
      timeout-minutes: 15

  test-windows-go122-utils:
    uses: ./.github/workflows/windows-optimization.yml
    with:
      go-version: '1.22'
      test-packages: './internal/hasher/... ./internal/logger/... ./internal/stats/... ./internal/verifier/...'
      coverage-flag: 'windows-go122-utils'
      timeout-minutes: 15

  test-windows-go122-integration:
    uses: ./.github/workflows/windows-optimization.yml
    with:
      go-version: '1.22'
      test-packages: './tests/...'
      coverage-flag: 'windows-go122-integration'
      timeout-minutes: 15

  # ビルドジョブ
  build:
    runs-on: ubuntu-latest
    needs: [
      test-linux, 
      test-linux-go122, 
      test-windows-core, 
      test-windows-internal, 
      test-windows-utils, 
      test-windows-integration,
      test-windows-go122-core,
      test-windows-go122-internal,
      test-windows-go122-utils,
      test-windows-go122-integration
    ]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.21-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.21-
            ${{ runner.os }}-go-

      - name: Setup build environment
        run: |
          mkdir -p build_output dist
          chmod 755 build_output dist

      - name: Build
        run: make build

      - name: Test build
        run: |
          echo "Testing build output..."
          ./gopier --help || exit 1
          ./gopier --create-config || exit 1
          echo "Build test completed successfully"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gopier-build-${{ github.sha }}
          path: |
            gopier
            build_output/
            dist/
          retention-days: 30 