name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21, 1.22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Run tests with coverage
        run: make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          flags: ${{ github.ref == 'refs/heads/develop' && 'develop' || 'unittests' }}
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: [1.21, 1.22]
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            ${{ runner.os }}-go-
      
      - name: Install dependencies
        run: go mod download
      
      - name: Verify Go installation
        run: |
          go version
          go env GOPATH
          go env GOROOT
          Write-Host "Go installation verified successfully"
      
      - name: Set environment variables
        run: |
          $env:CI = "true"
          $env:GITHUB_ACTIONS = "true"
          $env:TESTING = "1"
          Write-Host "Environment variables set"
      
      - name: Clean up previous test artifacts
        run: |
          Write-Host "Cleaning up previous test artifacts..."
          if (Test-Path "coverage.out") { Remove-Item "coverage.out" -Force }
          if (Test-Path "coverage.html") { Remove-Item "coverage.html" -Force }
          if (Test-Path "*.db") { Remove-Item "*.db" -Force }
          if (Test-Path "gopier.exe") { Remove-Item "gopier.exe" -Force }
          Write-Host "Cleanup completed"
      
      - name: Kill any hanging processes
        run: |
          Write-Host "Killing any hanging processes..."
          Get-Process | Where-Object {$_.ProcessName -like "*go*" -or $_.ProcessName -like "*gopier*"} | Stop-Process -Force -ErrorAction SilentlyContinue
          Write-Host "Process cleanup completed"
      
      - name: Build
        run: |
          Write-Host "Starting build process..."
          & .\build.ps1 build
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Build failed with exit code: $LASTEXITCODE"
            exit $LASTEXITCODE
          }
        shell: pwsh
        timeout-minutes: 10
      
      - name: Verify build output
        run: |
          if (Test-Path "gopier.exe") {
            Write-Host "✓ Build successful: gopier.exe exists"
            $size = (Get-Item "gopier.exe").Length / 1MB
            Write-Host "Executable size: $([math]::Round($size, 2)) MB"
            & .\gopier.exe --help
          } else {
            Write-Host "✗ Build failed: gopier.exe not found"
            Get-ChildItem -Name
            exit 1
          }
        shell: pwsh
      
      - name: Test
        run: |
          Write-Host "Starting tests..."
          $env:CI = "true"
          $env:GITHUB_ACTIONS = "true"
          $env:TESTING = "1"
          & .\build.ps1 test
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Tests failed with exit code: $LASTEXITCODE"
            exit $LASTEXITCODE
          }
          Write-Host "Tests completed successfully"
        shell: pwsh
        timeout-minutes: 15
      
      - name: Coverage
        run: |
          Write-Host "Starting coverage tests..."
          $env:CI = "true"
          $env:GITHUB_ACTIONS = "true"
          $env:TESTING = "1"
          & .\build.ps1 test-coverage
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Coverage tests failed with exit code: $LASTEXITCODE"
            exit $LASTEXITCODE
          }
          Write-Host "Coverage tests completed successfully"
        shell: pwsh
        timeout-minutes: 15
      
      - name: Verify coverage file
        run: |
          if (Test-Path "coverage.out") {
            Write-Host "✓ Coverage file generated: coverage.out"
            $size = (Get-Item "coverage.out").Length
            Write-Host "Coverage file size: $size bytes"
          } else {
            Write-Host "✗ Coverage file not found"
            Get-ChildItem -Name
            exit 1
          }
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          flags: windows
          name: codecov-windows
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            ${{ runner.os }}-go-

      - name: Build
        run: make build

      - name: Test build
        run: |
          ./gopier --help
          ./gopier --create-config 