name: Setup Go Environment

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version to use'
        required: false
        default: '1.21'
        type: string
    outputs:
      go-version:
        description: 'The Go version that was set up'
        value: ${{ jobs.setup.outputs.go-version }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.set-go-version.outputs.version }}
    steps:
      - name: Set Go version
        id: set-go-version
        run: echo "version=${{ inputs.go-version }}" >> $GITHUB_OUTPUT 