name: Sign Release Assets

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
    branches:
      - master

jobs:
  sign:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download release assets
        uses: actions/download-artifact@v4
        with:
          name: release-assets

      - name: Setup GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback --edit-key "${{ secrets.GPG_KEY_ID }}" trust
          gpg --list-keys

      - name: Sign artifacts
        run: |
          # 署名ファイルを作成
          for file in *.tar.gz *.zip; do
            if [ -f "$file" ]; then
              echo "Signing $file..."
              echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback --detach-sign --armor "$file"
              echo "Created signature: $file.asc"
            fi
          done

      - name: Upload signed artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-assets
          path: |
            *.tar.gz
            *.tar.gz.asc
            *.zip
            *.zip.asc 